// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdV8Cqk9jEh4fbkZHZdu594Nhdo9bRTl4',
    appId: '1:189043644646:web:719c911be7628a3ec70327',
    messagingSenderId: '189043644646',
    projectId: 'blooddonation-a88a2',
    authDomain: 'blooddonation-a88a2.firebaseapp.com',
    storageBucket: 'blooddonation-a88a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxlQaa7_z3Sxg2fDKipCCVk3WEt01f-V0',
    appId: '1:189043644646:android:4acd30b049ef3d58c70327',
    messagingSenderId: '189043644646',
    projectId: 'blooddonation-a88a2',
    storageBucket: 'blooddonation-a88a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG-XonDUEyRdfcIr0uNZsO2aWtnv7Pekg',
    appId: '1:189043644646:ios:b73edc8c63272f09c70327',
    messagingSenderId: '189043644646',
    projectId: 'blooddonation-a88a2',
    storageBucket: 'blooddonation-a88a2.firebasestorage.app',
    iosBundleId: 'com.blooddonation.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG-XonDUEyRdfcIr0uNZsO2aWtnv7Pekg',
    appId: '1:189043644646:ios:ca2c17e219feb9d9c70327',
    messagingSenderId: '189043644646',
    projectId: 'blooddonation-a88a2',
    storageBucket: 'blooddonation-a88a2.firebasestorage.app',
    iosBundleId: 'com.example.blooddonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdV8Cqk9jEh4fbkZHZdu594Nhdo9bRTl4',
    appId: '1:189043644646:web:1c5b902692adf50fc70327',
    messagingSenderId: '189043644646',
    projectId: 'blooddonation-a88a2',
    authDomain: 'blooddonation-a88a2.firebaseapp.com',
    storageBucket: 'blooddonation-a88a2.firebasestorage.app',
  );
}
